version: "3.7"
services:
  fanfare:
    container_name: fanfare
    build: .
    restart: always
    environment:
      - TOKEN=[your token here] # https://discord.com/developers/applications
      - GUILD= # if set, the commands will only be available in this guild whose ID is linked here
      - SKIP_COMMAND_VALIDATION=false # if set to true, the bot will not check if the commands are up to date
      - STATUS="" # The status message you want the bot to have.
      - SQLITE_PATH=/data/database.sqlite # the path to the database file
      - DATABASE_DRIVER=sqlite # sqlite is the only driver supported for now but feel free to add more
    volumes:
      - fanfare:/data/
volumes:
    fanfare:
